### ISSUE TITLE
400 AUTH_BYTES_INVALID

### ISSUE THREAD

**Issue by bidbiz** [weebzone/Surf-TG#8]
The thumbnail does not appear and the error log is as follows:
pyrogram.errors.exceptions.bad_request_400.AuthBytesInvalid: Telegram says: [400 AUTH_BYTES_INVALID] - The authorization bytes are invalid (caused by "auth.ImportAuthorization")

**Comment by SilentDemonSD** [comment]
Generate STRING_SESSION from pyrofork latest in Collab Method
